[project]
name = "giis-srv-selector"
version = "0.2.0"
description = "GUI утилита для управления stunnel конфигурацией на Windows"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.16.0",
]
